### ISSUE TITLE
Band Split: Inserting FX inside Band Split locates FX in the wrong position

### ISSUE THREAD

**Issue by Suzuki-Re** [BryanChi/BryanChi-FX-Devices#41]
Gif says it all
![splitfx](https://github.com/BryanChi/BryanChi-FX-Devices/assets/101462564/e75e06a3-d665-4f6d-98d9-f4466c32b52a)

**Comment by BryanChi** [comment]
I think there is still weird things happening  if you do certain things in certain order, but I can't figure out how to replicate. please let me know if you find how to replicate it.
