### ISSUE TITLE
Pro-Q3: Pro-Q3 layout works weird

### ISSUE THREAD

**Issue by Suzuki-Re** [BryanChi/BryanChi-FX-Devices#43]
![proq](https://github.com/BryanChi/BryanChi-FX-Devices/assets/101462564/8d61d10f-01e9-4f3f-806a-c88a4a7b7f82)

The layout itself is a bit off (no title bar = can't remove it by alt clicking it).
![reaper_n2c0x86QFr](https://github.com/BryanChi/BryanChi-FX-Devices/assets/101462564/932e9719-acb1-452c-904b-c7f34730a77e)

**Comment by BryanChi** [comment]
thank you, it's fixed just now!
