### ISSUE TITLE
Running the first FX in parallel with the previous FX crashes

### ISSUE THREAD

**Issue by Suzuki-Re** [BryanChi/BryanChi-FX-Devices#69]
Technically we can run the very first FX in parallel with the previous FX in the native FX window although there's no "previous" FX, and we can move it to the location after another FX afterwards or whatever. Maybe we should think about what the best design is in this case instead of crashing.

```
Error: GUI.lua:2399: attempt to index a nil value (field '?')

Stack traceback:
	GUI.lua:2399: in local 'If_Parallel_FX'
	GUI.lua:2442: in function 'createFXWindow'
	BryanChi_FX Devices.lua:440: in local 'Create_FX_Window'
	BryanChi_FX Devices.lua:2368: in function 'loop'
		[C]: in function 'xpcall'
	General Functions.lua:1519: in function <...\BryanChi_FX_Devices\src\Functions\General Functions.lua:1518>

Reaper:       	7.18+dev0716/x64
Platform:     	Win64
```

**Comment by BryanChi** [comment]
Were you using version beta 15?  I added some lines to automatically set the first fx to not parallel with previous fx. but not sure when that's added. Anyway the crash is fixed in the latest version.
